### ISSUE TITLE
Weirdly, the  Flesh-Out-Data branch is NOT merged in but GitHub THi

### ISSUE THREAD

**Issue by llorracc** [econ-ark/REMARK-starter-example#6]

**Comment by llorracc** [comment]
Therefore a request to merge is denied.

**Comment by MridulS** [comment]
looks like there was a wrong push to this repo https://github.com/econ-ark/REMARK-starter-example/commit/3014728beaaf64cb2c6a4515193d3f4cddbed4fb I think this was meant for `PortfolioChoiceWithRiskyHousing` ?

**Comment by llorracc** [comment]
Yes, clearly you're right.  Not quite sure how that happened.

Can you fix it?

**Comment by MridulS** [comment]
I did revert the last 2 commits.
In https://github.com/econ-ark/REMARK-starter-example/commit/0df5d80fd4a82b4ec677fb2f6b474cca8de173af the python file of the jupyter notebook is not a "linked" jupytext file, is that on purpose?
